services:
  - type: web
    name: talentlink-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn talentlink.talentlink.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: talentlink.talentlink.settings
    rootDir: .
